# Generated by Django 4.2.1 on 2023-05-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_serial', models.TextField(default='', max_length=100, unique=True)),
                ('engine_serial', models.TextField(default='', max_length=100, unique=True)),
                ('transmission_serial', models.TextField(default='', max_length=100, unique=True)),
                ('driving_bridge_serial', models.TextField(default='', max_length=100, unique=True)),
                ('controlled_bridge_serial', models.TextField(default='', max_length=100, unique=True)),
                ('contract', models.TextField(default='', max_length=100, unique=True)),
                ('shipment_date', models.DateField(auto_now_add=True)),
                ('counteragent', models.TextField(default='')),
                ('shipment_address', models.TextField(default='')),
                ('equipment', models.TextField(default='')),
                ('client_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_client_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MM', 'Machine Model'), ('EM', 'Engine Model'), ('TM', 'Transmission Model'), ('DM', 'Driving Bridge Model'), ('CM', 'Controlled Bridge Model'), ('MT', 'Maintenance Type'), ('FT', 'Failure Type'), ('RT', 'Repair Type'), ('SC', 'Service Company')], max_length=2)),
                ('title', models.TextField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(auto_now_add=True)),
                ('operating_time', models.IntegerField(default=0)),
                ('failure_description', models.TextField(default='')),
                ('used_consumables', models.TextField(default='')),
                ('repair_date', models.DateField()),
                ('downtime', models.IntegerField(default=0)),
                ('failure_component', models.ForeignKey(limit_choices_to=main.models.ReferenceTable.get_component_qfilter, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_failure_component', to='main.referencetable')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine')),
                ('repair_type', models.ForeignKey(limit_choices_to={'type': 'RT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_repair_type', to='main.referencetable')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('operating_time', models.IntegerField(default=0)),
                ('order_number', models.TextField(default='')),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_company', models.ForeignKey(limit_choices_to={'type': 'SC'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_company', to='main.referencetable')),
                ('type', models.ForeignKey(limit_choices_to={'type': 'MT'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='main.referencetable')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='controlled_bridge',
            field=models.ForeignKey(limit_choices_to={'type': 'CM'}, on_delete=django.db.models.deletion.CASCADE, related_name='machine_controlled_bridge', to='main.referencetable'),
        ),
        migrations.AddField(
            model_name='machine',
            name='driving_bridge',
            field=models.ForeignKey(limit_choices_to={'type': 'DM'}, on_delete=django.db.models.deletion.CASCADE, related_name='machine_driving_bridge', to='main.referencetable'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine',
            field=models.ForeignKey(limit_choices_to={'type': 'EM'}, on_delete=django.db.models.deletion.CASCADE, related_name='machine_engine', to='main.referencetable'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(limit_choices_to={'type': 'MM'}, on_delete=django.db.models.deletion.CASCADE, related_name='machine_model', to='main.referencetable'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_service_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission',
            field=models.ForeignKey(limit_choices_to={'type': 'TM'}, on_delete=django.db.models.deletion.CASCADE, related_name='machine_transmission', to='main.referencetable'),
        ),
    ]
