# Generated by Django 4.2.1 on 2023-05-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='downtime',
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failure_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='repair_date',
            field=models.DateTimeField(),
        ),
    ]
